### ISSUE TITLE
Loading Screen

### ISSUE THREAD

**Issue by stewluj** [AriGlockner/Raven-s-Adventure#2]
Perhaps it's just my computer, but screen would pause on just part of an image of a robot after the "Ari Glockner" intro flashed. Tried fixing this by full-screening, but all I saw was  a screen with a r on it covered by a picture of raven

**Comment by AriGlockner** [comment]
Thanks for telling me about this issue.

If I understand you correctly, this is what your screen looks like:
<img width="1598" alt="Screen Shot 2020-12-31 at 2 32 35 PM" src="https://user-images.githubusercontent.com/44281741/103427387-98b22280-4b75-11eb-85e5-424cf525e0a3.png">

I will be redoing my Main Menu Screens and Pause Screens in the next update and that should fix the problem you were dealing with. Until the next update is out, I will keep this issue open. In the meantime, just sit tight and relax as I work on this issue.

**Comment by AriGlockner** [comment]
The Achievement screen isn't working at the moment, but I will be fixing that soon. My next update will fix that, but it should now be in a playable state.
